#!/usr/bin/env python
# coding=utf-8
# Created by sharp.gan at 2017-04-22
# Above automatically generated by github.com/supersu097/EZcode4CLI

import argparse

def args_process():
    parser = argparse.ArgumentParser(
        description='A tool to compute an interesting math guess')
    parser.add_argument(
        '-i', '--initialNum',
        help='The number(>=10) u wanna computer at the beginning',
        type=int,
        required=True)
    args = parser.parse_args()
    return args

def initial_number_check():
    if args_process().initialNum < 10:
        exit('Pls specify a number which is equal or larger than 10')

def main():
    i = args_process().initialNum
    while True:
        former = str(i)[:-1]
        latter = str(i)[-1]
        normal_result = i-int(former)*9
        reverse_analysis = int(former)+int(latter)
        if normal_result == reverse_analysis:
            output = str(i) + "-" + former + "*9= " + str(normal_result) + \
                " << " + former + "+" + latter + "= " + str(reverse_analysis)
            print output
            # with open("/sdcard/output.log", "a+") as log:
            #    print >> log, output
        else:
            print "Abort:" + str(i)
            break
        i += 1

if __name__ == '__main__':
    initial_number_check()
    main()
